version: '3.9'
services:
  rest-api-gateway-cs:
    build:
      context: ./rest-api-gateway
      dockerfile: Dockerfile
    container_name: diploma_rest_gateway_cs
    restart: unless-stopped
    environment:
      - PORT=3010
      - USERS_SERVICE_URL=http://${USERS_HOST:-10.186.0.6}:3012
      - ORDERS_SERVICE_URL=http://${ORDERS_HOST:-10.186.0.4}:3014
    ports:
      - '3010:3010'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - diploma_default

  rpc-api-gateway-cs:
    build:
      context: ./rpc-api-gateway
      dockerfile: Dockerfile
    container_name: diploma_rpc_gateway_cs
    restart: unless-stopped
    environment:
      - PORT=3011
      - USERS_SERVICE_GRPC_URL=http://${USERS_HOST:-10.186.0.6}:5013
      - ORDERS_SERVICE_GRPC_URL=http://${ORDERS_HOST:-10.186.0.4}:5015

    ports:
      - '3011:3011'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - diploma_default

networks:
  diploma_default:
    external: true
