version: '3.9'
services:
  rest-api-gateway-cs:
    build:
      context: ./rest-api-gateway
      dockerfile: Dockerfile
    container_name: diploma_rest_gateway_cs
    restart: unless-stopped
    environment:
      - PORT=3010
      - USERS_SERVICE_URL=http://diploma_users_rest_cs:3012
      - ORDERS_SERVICE_URL=http://diploma_orders_rest_cs:3014
    ports:
      - '3010:3010'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - diploma_default

  rpc-api-gateway-cs:
    build:
      context: ./rpc-api-gateway
      dockerfile: Dockerfile
    container_name: diploma_rpc_gateway_cs
    restart: unless-stopped
    environment:
      - PORT=3011
      - USERS_SERVICE_GRPC_URL=http://diploma_users_rpc_cs:5013
      - ORDERS_SERVICE_GRPC_URL=http://diploma_orders_rpc_cs:5015
    ports:
      - '3011:3011'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - diploma_default

networks:
  diploma_default:
    external: true
